### ISSUE TITLE
关于Readme里面后台执行的那条命令

### ISSUE THREAD

**Issue by alone-wolf** [TSIOJeft/WeChatPush#4]
理论上可以使用如下命令实现，在 Linux、MacOS 系统中均可使用，包括termux

这里是要执行的命令 > /dev/null 2>&1 &

**Comment by TSIOJeft** [comment]
嗯？没明白啥意思

**Comment by alone-wolf** [comment]
用我写的这条命令把程序挂到后台比较优雅就是了，另外可以将 /dev/null 换成文件路径，将程序的回显重定向到文件的输入流，随手记录log
